name: A workflow for my Hello World file
on: 
   workflow_dispatch:
jobs:
  build-job:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
    - name: Echo Hello World
      run: echo Hello World
    - name: Index.html Content
      run: |
          echo Hello World2
          cat Index.html
          cat Courses.html
    
    
